INSERT INTO "articles" ("slug", "title", "excerpt", "body", "category", "author", "published_at", "featured", "tags") VALUES
('lsmg-rolling-loud-press-coverage', 'Inside LSMG''s Rolling Loud Press Coverage', 'A LEDGERA field note on LSMG''s credentialed coverage of Rolling Loud and the stories captured around the festival.', 'LSMG covered Rolling Loud as credentialed press, documenting the artists, audience, and business surrounding one of hip-hop''s largest festival stages. This dispatch serves as the reading destination for that coverage record and will collect related interviews, video, and festival features as they are published.', 'Music', 'A LEDGERA Dispatch', '2026-07-29 12:00:00+00', false, ARRAY['lsmg coverage','rolling loud','press credential']),
('lsmg-texas-rangers-press-coverage', 'LSMG at the Texas Rangers: A Sports Media Field Note', 'A LEDGERA field note documenting LSMG''s Texas Rangers sports-media coverage.', 'LSMG''s sports-media work includes on-site coverage connected to the Texas Rangers. This dispatch records that credentialed access and provides a home for related reporting, interviews, photography, and video as the archive expands.', 'Sports', 'A LEDGERA Dispatch', '2026-07-29 11:00:00+00', false, ARRAY['lsmg coverage','texas rangers','press credential']),
('lsmg-dallas-cowboys-press-coverage', 'LSMG''s Dallas Cowboys Coverage Archive', 'A LEDGERA field note documenting LSMG''s on-site Dallas Cowboys editorial access.', 'LSMG has covered the Dallas Cowboys through on-site editorial access. This dispatch connects that coverage claim to a dedicated archive for reporting, interviews, photography, and video produced around the team.', 'Sports', 'A LEDGERA Dispatch', '2026-07-29 10:00:00+00', false, ARRAY['lsmg coverage','dallas cowboys','press credential']),
('lsmg-comic-con-press-coverage', 'From the Floor: LSMG''s Comic Con Coverage', 'A LEDGERA field note on LSMG''s entertainment reporting, panels, and interviews from Comic Con.', 'LSMG''s Comic Con coverage focuses on entertainment reporting, panel access, creator conversations, and the cultural stories moving through the convention floor. This dispatch provides a permanent destination for that work as new coverage is added.', 'Entertainment', 'A LEDGERA Dispatch', '2026-07-29 09:00:00+00', false, ARRAY['lsmg coverage','comic con','press credential']),
('lsmg-wwe-press-coverage', 'Ringside: LSMG''s WWE Media Coverage', 'A LEDGERA field note documenting LSMG''s WWE event access and talent-focused entertainment coverage.', 'LSMG''s WWE coverage includes event access and talent-focused entertainment reporting. This dispatch connects that credential record to a growing archive of interviews, features, photography, and video.', 'Entertainment', 'A LEDGERA Dispatch', '2026-07-29 08:00:00+00', false, ARRAY['lsmg coverage','wwe','press credential']),
('lsmg-morehouse-gala-press-coverage', 'LSMG Covers the Morehouse Gala', 'A LEDGERA field note documenting LSMG''s coverage of the Morehouse College gala.', 'LSMG covered the Morehouse College gala as a major cultural and community event. This dispatch provides a permanent home for the resulting reporting, photography, interviews, and future updates connected to the event.', 'Culture', 'A LEDGERA Dispatch', '2026-07-29 07:00:00+00', false, ARRAY['lsmg coverage','morehouse gala','press coverage']),
('the-last-shot-podcast-listening-guide', 'The Last Shot Podcast: Watch, Listen, and Follow the Conversation', 'A LEDGERA guide to The Last Shot Podcast video and audio catalog across Spotify, Apple Podcasts, and YouTube.', 'The Last Shot Podcast brings together conversations about music, culture, media, and the business behind creative work. Watch and listen through the embedded players on LSMG''s Watch page, then follow the show on Spotify, Apple Podcasts, and YouTube for the complete episode catalog. This guide remains the editorial home for episode notes and related LEDGERA coverage.', 'Podcast', 'A LEDGERA Dispatch', '2026-07-29 06:00:00+00', false, ARRAY['lsmg coverage','podcast','the last shot podcast'])
ON CONFLICT ("slug") DO NOTHING;
