/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrRouteImport } from './routes/pr'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TribecaIndexRouteImport } from './routes/tribeca.index'
import { Route as CultureLedgerIndexRouteImport } from './routes/culture-ledger.index'
import { Route as TribecaScheduleRouteImport } from './routes/tribeca.schedule'
import { Route as ModelsSlugRouteImport } from './routes/models_.$slug'
import { Route as CultureLedgerArticleSlugRouteImport } from './routes/culture-ledger.$articleSlug'
import { Route as TribecaFilmsFilmSlugRouteImport } from './routes/tribeca.films.$filmSlug'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrRoute = PrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribecaIndexRoute = TribecaIndexRouteImport.update({
  id: '/tribeca/',
  path: '/tribeca/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureLedgerIndexRoute = CultureLedgerIndexRouteImport.update({
  id: '/culture-ledger/',
  path: '/culture-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribecaScheduleRoute = TribecaScheduleRouteImport.update({
  id: '/tribeca/schedule',
  path: '/tribeca/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models_/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureLedgerArticleSlugRoute =
  CultureLedgerArticleSlugRouteImport.update({
    id: '/culture-ledger/$articleSlug',
    path: '/culture-ledger/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const TribecaFilmsFilmSlugRoute = TribecaFilmsFilmSlugRouteImport.update({
  id: '/tribeca/films/$filmSlug',
  path: '/tribeca/films/$filmSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/models': typeof ModelsRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/tribeca/schedule': typeof TribecaScheduleRoute
  '/culture-ledger/': typeof CultureLedgerIndexRoute
  '/tribeca/': typeof TribecaIndexRoute
  '/tribeca/films/$filmSlug': typeof TribecaFilmsFilmSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/models': typeof ModelsRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/tribeca/schedule': typeof TribecaScheduleRoute
  '/culture-ledger': typeof CultureLedgerIndexRoute
  '/tribeca': typeof TribecaIndexRoute
  '/tribeca/films/$filmSlug': typeof TribecaFilmsFilmSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/models': typeof ModelsRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/models_/$slug': typeof ModelsSlugRoute
  '/tribeca/schedule': typeof TribecaScheduleRoute
  '/culture-ledger/': typeof CultureLedgerIndexRoute
  '/tribeca/': typeof TribecaIndexRoute
  '/tribeca/films/$filmSlug': typeof TribecaFilmsFilmSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/media'
    | '/models'
    | '/pr'
    | '/press'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/models/$slug'
    | '/tribeca/schedule'
    | '/culture-ledger/'
    | '/tribeca/'
    | '/tribeca/films/$filmSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/media'
    | '/models'
    | '/pr'
    | '/press'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/models/$slug'
    | '/tribeca/schedule'
    | '/culture-ledger'
    | '/tribeca'
    | '/tribeca/films/$filmSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/media'
    | '/models'
    | '/pr'
    | '/press'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/models_/$slug'
    | '/tribeca/schedule'
    | '/culture-ledger/'
    | '/tribeca/'
    | '/tribeca/films/$filmSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  ModelsRoute: typeof ModelsRoute
  PrRoute: typeof PrRoute
  PressRoute: typeof PressRoute
  WatchRoute: typeof WatchRoute
  CultureLedgerArticleSlugRoute: typeof CultureLedgerArticleSlugRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  TribecaScheduleRoute: typeof TribecaScheduleRoute
  CultureLedgerIndexRoute: typeof CultureLedgerIndexRoute
  TribecaIndexRoute: typeof TribecaIndexRoute
  TribecaFilmsFilmSlugRoute: typeof TribecaFilmsFilmSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr': {
      id: '/pr'
      path: '/pr'
      fullPath: '/pr'
      preLoaderRoute: typeof PrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribeca/': {
      id: '/tribeca/'
      path: '/tribeca'
      fullPath: '/tribeca/'
      preLoaderRoute: typeof TribecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture-ledger/': {
      id: '/culture-ledger/'
      path: '/culture-ledger'
      fullPath: '/culture-ledger/'
      preLoaderRoute: typeof CultureLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribeca/schedule': {
      id: '/tribeca/schedule'
      path: '/tribeca/schedule'
      fullPath: '/tribeca/schedule'
      preLoaderRoute: typeof TribecaScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/$slug': {
      id: '/models_/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture-ledger/$articleSlug': {
      id: '/culture-ledger/$articleSlug'
      path: '/culture-ledger/$articleSlug'
      fullPath: '/culture-ledger/$articleSlug'
      preLoaderRoute: typeof CultureLedgerArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribeca/films/$filmSlug': {
      id: '/tribeca/films/$filmSlug'
      path: '/tribeca/films/$filmSlug'
      fullPath: '/tribeca/films/$filmSlug'
      preLoaderRoute: typeof TribecaFilmsFilmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  ModelsRoute: ModelsRoute,
  PrRoute: PrRoute,
  PressRoute: PressRoute,
  WatchRoute: WatchRoute,
  CultureLedgerArticleSlugRoute: CultureLedgerArticleSlugRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  TribecaScheduleRoute: TribecaScheduleRoute,
  CultureLedgerIndexRoute: CultureLedgerIndexRoute,
  TribecaIndexRoute: TribecaIndexRoute,
  TribecaFilmsFilmSlugRoute: TribecaFilmsFilmSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
