/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrRouteImport } from './routes/pr'
import { Route as MemberPortalRouteImport } from './routes/member-portal'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreativeOsRouteImport } from './routes/creative-os'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CultureLedgerIndexRouteImport } from './routes/culture-ledger.index'
import { Route as CultureLedgerArticleSlugRouteImport } from './routes/culture-ledger.$articleSlug'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrRoute = PrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberPortalRoute = MemberPortalRouteImport.update({
  id: '/member-portal',
  path: '/member-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeOsRoute = CreativeOsRouteImport.update({
  id: '/creative-os',
  path: '/creative-os',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureLedgerIndexRoute = CultureLedgerIndexRouteImport.update({
  id: '/culture-ledger/',
  path: '/culture-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureLedgerArticleSlugRoute =
  CultureLedgerArticleSlugRouteImport.update({
    id: '/culture-ledger/$articleSlug',
    path: '/culture-ledger/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/creative-os': typeof CreativeOsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/member-portal': typeof MemberPortalRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/upload': typeof UploadRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/culture-ledger/': typeof CultureLedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/creative-os': typeof CreativeOsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/member-portal': typeof MemberPortalRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/upload': typeof UploadRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/culture-ledger': typeof CultureLedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/creative-os': typeof CreativeOsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/member-portal': typeof MemberPortalRoute
  '/pr': typeof PrRoute
  '/press': typeof PressRoute
  '/upload': typeof UploadRoute
  '/watch': typeof WatchRoute
  '/culture-ledger/$articleSlug': typeof CultureLedgerArticleSlugRoute
  '/culture-ledger/': typeof CultureLedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-login'
    | '/booking'
    | '/contact'
    | '/creative-os'
    | '/login'
    | '/media'
    | '/member-portal'
    | '/pr'
    | '/press'
    | '/upload'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/culture-ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/booking'
    | '/contact'
    | '/creative-os'
    | '/login'
    | '/media'
    | '/member-portal'
    | '/pr'
    | '/press'
    | '/upload'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/culture-ledger'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-login'
    | '/booking'
    | '/contact'
    | '/creative-os'
    | '/login'
    | '/media'
    | '/member-portal'
    | '/pr'
    | '/press'
    | '/upload'
    | '/watch'
    | '/culture-ledger/$articleSlug'
    | '/culture-ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  CreativeOsRoute: typeof CreativeOsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  MemberPortalRoute: typeof MemberPortalRoute
  PrRoute: typeof PrRoute
  PressRoute: typeof PressRoute
  UploadRoute: typeof UploadRoute
  WatchRoute: typeof WatchRoute
  CultureLedgerArticleSlugRoute: typeof CultureLedgerArticleSlugRoute
  CultureLedgerIndexRoute: typeof CultureLedgerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr': {
      id: '/pr'
      path: '/pr'
      fullPath: '/pr'
      preLoaderRoute: typeof PrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-portal': {
      id: '/member-portal'
      path: '/member-portal'
      fullPath: '/member-portal'
      preLoaderRoute: typeof MemberPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-os': {
      id: '/creative-os'
      path: '/creative-os'
      fullPath: '/creative-os'
      preLoaderRoute: typeof CreativeOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture-ledger/': {
      id: '/culture-ledger/'
      path: '/culture-ledger'
      fullPath: '/culture-ledger/'
      preLoaderRoute: typeof CultureLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture-ledger/$articleSlug': {
      id: '/culture-ledger/$articleSlug'
      path: '/culture-ledger/$articleSlug'
      fullPath: '/culture-ledger/$articleSlug'
      preLoaderRoute: typeof CultureLedgerArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  CreativeOsRoute: CreativeOsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  MemberPortalRoute: MemberPortalRoute,
  PrRoute: PrRoute,
  PressRoute: PressRoute,
  UploadRoute: UploadRoute,
  WatchRoute: WatchRoute,
  CultureLedgerArticleSlugRoute: CultureLedgerArticleSlugRoute,
  CultureLedgerIndexRoute: CultureLedgerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
